name: Azure Docker Nap
services:
  azure_docker_nap:
    image: azure_docker_nap:latest
    environment:
      - DATA_ROOT=/data
    volumes:
      - type: volume
        source: adn_data
        target: /data
        volume:
          nocopy: true
volumes:
  adn_data:
    name: adn_data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DATA_VOLUME}
